version: '3'
name: ocap-standalone

networks:
  overlay:
    driver: bridge
volumes:
  postgres_data:

services:
  db:
    image: postgres:12-alpine
    container_name: ocap-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-root}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@localhost:5432/$${POSTGRES_DB} || exit 1",
        ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d/:/docker-entrypoint-initdb.d/:ro
    networks:
      - overlay
  redis:
    image: redis:6-alpine
    container_name: ocap-redis
    mem_limit: 100m
    restart: unless-stopped
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    networks:
      - overlay
  olap:
    image: metadc/metad-olap:1.0.0
    deploy:
      replicas: 3
    restart: unless-stopped
    healthcheck:
      test: curl -m 5 --silent --fail --request GET http://localhost:8080/ | jq --exit-status -n 'inputs | if has("status") then .status=="UP" else false end' > /dev/null || exit 1
      interval: 10s
      timeout: 2s
      retries: 10
    links:
      - db:${DB_HOST:-db}
    environment:
      OLAP_REDIS_DATABASE: 1
      OLAP_REDIS_HOST: "redis"
      OLAP_REDIS_PORT: 6379
      OLAP_REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    networks:
      - overlay
  api:
    image: registry.cn-hangzhou.aliyuncs.com/metad/ocap-api:main
    container_name: ocap-api
    environment:
      INSTALLATION_MODE: ${INSTALLATION_MODE:-standalone}
      HOST: ${API_HOST:-api}
      PORT: 3000
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OLAP_HOST: olap
      OLAP_PORT: 8080
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      DEMO: ${DEMO:-false}
      SENTRY_DSN: ${SENTRY_DSN:-}
      LOGGER_LEVEL: ${LOGGER_LEVEL:-info}
    env_file:
      - .env
    command: ["node", "main.js"]
    restart: on-failure
    depends_on:
      - db
      - redis
    links:
      - db:${DB_HOST:-db}
    ports:
      - ${API_PORT:-3000}:3000
    volumes:
      - ./volumes/api/public:/srv/pangolin/public
    networks:
      - overlay
  webapp:
    image: registry.cn-hangzhou.aliyuncs.com/metad/ocap-webapp:main
    container_name: ocap-webapp
    environment:
      HOST: ${WEB_HOST:-webapp}
      NODE_ENV: ${NODE_ENV:-development}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL:-http://localhost:4200}
      SENTRY_DSN: ${SENTRY_DSN:-}
      DEFAULT_LATITUDE: ${DEFAULT_LATITUDE:-42.6459136}
      DEFAULT_LONGITUDE: ${DEFAULT_LONGITUDE:-23.3332736}
      DEFAULT_CURRENCY: ${DEFAULT_CURRENCY:-USD}
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-3000}
      ENABLE_LOCAL_AGENT: false
    env_file:
      - .env
    entrypoint: './entrypoint.compose.sh'
    command: ['nginx', '-g', 'daemon off;']
    # command: ['nginx', '-g', 'daemon off;', '-c', '/webapp/conf/nginx.conf']
    restart: on-failure
    links:
      - api:${API_HOST:-api}
    depends_on:
      - api
    ports:
      - ${WEBAPP_PORT:-80}:80
      # - ${WEBAPP_PORT:-443}:443
    volumes:
      - ./volumes/webapp/:/webapp/
    networks:
      - overlay
