version: '3'
services:
  fe:
    image: "apache/doris:1.2.2-fe-x86_64"
    container_name: "metad-fe"
    hostname: "fe"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - FE_ID=1
    ports:
      - 8030:8030
      - 9030:9030
    volumes:
      - ./doris/fe/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./doris/fe/conf:/opt/apache-doris/fe/conf
      - ./doris/fe/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.2
  be:
    image: "apache/doris:1.2.2-be-x86_64"
    container_name: "metad-be"
    hostname: "be"
    depends_on:
      - fe
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BE_ADDR=172.20.80.3:9050
    ports:
      - 8040:8040
    volumes:
      - ./doris/be/storage:/opt/apache-doris/be/storage
      - ./doris/be/conf:/opt/apache-doris/be/conf
      - ./doris/be/script:/docker-entrypoint-initdb.d
      - ./doris/be/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
  db:
    image: postgres:12-alpine
    container_name: metad-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-root}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@localhost:5432/$${POSTGRES_DB} || exit 1",
        ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d/:/docker-entrypoint-initdb.d/:ro
    # ports:
    #     - ${DB_PORT:-5432}:5432
    networks:
      - overlay
  redis:
    image: redis:6-alpine
    container_name: metad-redis
    mem_limit: 100m
    restart: unless-stopped
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    # ports:
    #     - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    networks:
      - overlay
  olap:
    image: metadc/metad-olap:1.0.0-rc.36
    container_name: metad-olap
    mem_limit: 1024m
    restart: always
    links:
      - db:${DB_HOST:-db}
      - fe:${DORIS_HOST:-doris}
    environment:
      OLAP_REDIS_DATABASE: 1
      OLAP_REDIS_HOST: "redis"
      OLAP_REDIS_PORT: 6379
      OLAP_REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    networks:
      - overlay
      - doris_net
  api:
    image: metadc/metad-api:1.3.8
    container_name: metad-api
    environment:
      HOST: ${API_HOST:-api}
      PORT: 3000
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OLAP_HOST: olap
      OLAP_PORT: 8080
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      SENTRY_DSN: ${SENTRY_DSN:-}
      LOGGER_LEVEL: ${LOGGER_LEVEL:-info}
    env_file:
      - .env
    command: ["node", "main.js"]
    restart: on-failure
    depends_on:
      - db
      - redis
    links:
      - db:${DB_HOST:-db}
      - fe:${DORIS_HOST:-doris}
    ports:
      - ${API_PORT:-3000}:3000
    volumes:
      - ./public:/srv/pangolin/apps/
    networks:
      - overlay
      - doris_net
  webapp:
    image: metadc/metad-webapp:1.3.8
    container_name: metad-webapp
    environment:
      HOST: ${WEB_HOST:-webapp}
      PORT: 4200
      NODE_ENV: ${NODE_ENV:-development}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL:-http://localhost:4200}
      SENTRY_DSN: ${SENTRY_DSN:-}
      DEFAULT_LATITUDE: ${DEFAULT_LATITUDE:-42.6459136}
      DEFAULT_LONGITUDE: ${DEFAULT_LONGITUDE:-23.3332736}
      DEFAULT_CURRENCY: ${DEFAULT_CURRENCY:-USD}
      DEMO: "true"
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-3000}
    env_file:
      - .env
    restart: on-failure
    links:
      - api:${API_HOST:-api}
    depends_on:
      - api
    ports:
      - ${WEBAPP_PORT:-80}:4200
    networks:
      - overlay

networks:
  overlay:
    driver: bridge
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/16
volumes:
  postgres_data:
