version: '3'
name: 'ocap-with-doris-3x'

services:
  fe-01:
    image: "apache/doris:1.2.2-fe-x86_64"
    container_name: "doris-fe-01"
    hostname: "fe-01"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - FE_ID=1
    ports:
      - 8031:8030
      - 9031:9030
    volumes:
      - ./doris/fe-01/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./doris/fe-01/conf:/opt/apache-doris/fe/conf
      - ./doris/fe-01/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.2
  fe-02:
    image: "apache/doris:1.2.2-fe-x86_64"
    container_name: "doris-fe-02"
    hostname: "fe-02"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - FE_ID=2
    ports:
      - 8032:8030
      - 9032:9030
    volumes:
      - ./doris/fe-02/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./doris/fe-02/conf:/opt/apache-doris/fe/conf
      - ./doris/fe-02/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.3
  fe-03:
    image: "apache/doris:1.2.2-fe-x86_64"
    container_name: "doris-fe-03"
    hostname: "fe-03"
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - FE_ID=3
    ports:
      - 8033:8030
      - 9033:9030
    volumes:
      - ./doris/fe-03/doris-meta:/opt/apache-doris/fe/doris-meta
      - ./doris/fe-03/conf:/opt/apache-doris/fe/conf
      - ./doris/fe-03/log:/opt/apache-doris/fe/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.4
  be-01:
    image: "apache/doris:1.2.2-be-x86_64"
    container_name: "doris-be-01"
    hostname: "be-01"
    depends_on:
      - fe-01
      - fe-02
      - fe-03
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - BE_ADDR=172.20.80.5:9050
      - DORIS_ROOT_PASS=${DORIS_ROOT_PASS:-}
    ports:
      - 8041:8040
    volumes:
      - ./doris/be-01/storage:/opt/apache-doris/be/storage
      - ./doris/be-01/conf:/opt/apache-doris/be/conf
      - ./doris/be-01/log:/opt/apache-doris/be/log
      - ./initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      doris_net:
        ipv4_address: 172.20.80.5
  be-02:
    image: "apache/doris:1.2.2-be-x86_64"
    container_name: "doris-be-02"
    hostname: "be-02"
    depends_on:
      - fe-01
      - fe-02
      - fe-03
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - BE_ADDR=172.20.80.6:9050
    ports:
      - 8042:8040
    volumes:
      - ./doris/be-02/storage:/opt/apache-doris/be/storage
      - ./doris/be-02/conf:/opt/apache-doris/be/conf
      - ./doris/be-02/script:/docker-entrypoint-initdb.d
      - ./doris/be-02/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.6
  be-03:
    image: "apache/doris:1.2.2-be-x86_64"
    container_name: "doris-be-03"
    hostname: "be-03"
    depends_on:
      - fe-01
      - fe-02
      - fe-03
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010,fe2:172.20.80.3:9010,fe3:172.20.80.4:9010
      - BE_ADDR=172.20.80.7:9050
    ports:
      - 8043:8040
    volumes:
      - ./doris/be-03/storage:/opt/apache-doris/be/storage
      - ./doris/be-03/conf:/opt/apache-doris/be/conf
      - ./doris/be-03/script:/docker-entrypoint-initdb.d
      - ./doris/be-03/log:/opt/apache-doris/be/log
    networks:
      doris_net:
        ipv4_address: 172.20.80.7
  balancer:
    image: nginx:latest
    container_name: "doris-balancer"
    hostname: "balancer"
    ports:
      - 9030:9030
      - 8030:8030
    #command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
    networks:
      doris_net:
        ipv4_address: 172.20.80.11
  db:
    image: postgres:12-alpine
    container_name: metad-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-root}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql postgres://$${POSTGRES_USER}:$${POSTGRES_PASSWORD}@localhost:5432/$${POSTGRES_DB} || exit 1",
        ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.d/:/docker-entrypoint-initdb.d/:ro
    # ports:
    #     - ${DB_PORT:-5432}:5432
    networks:
      - overlay
  # adminer:
  #   image: adminer
  #   container_name: metad-adminer
  #   restart: always
  #   links:
  #     - db:${DB_HOST:-db}
  #     - balancer:${DORIS_HOST:-doris}
  #   environment:
  #     ADMINER_DEFAULT_DB_DRIVER: pgsql
  #     ADMINER_DEFAULT_DB_HOST: ${DB_HOST:-db}
  #     ADMINER_DEFAULT_DB_NAME: ${DB_NAME:-postgres}
  #     ADMINER_DEFAULT_DB_PASSWORD: ${DB_PASS:-root}
  #   ports:
  #     - "8084:8080"
  #   networks:
  #     - overlay
  #     - doris_net
  redis:
    image: redis:6-alpine
    container_name: metad-redis
    mem_limit: 100m
    restart: unless-stopped
    command: ["sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}"]
    # ports:
    #     - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    networks:
      - overlay
  olap:
    image: metadc/metad-olap:1.0.0
    container_name: metad-olap
    restart: unless-stopped
    # ports:
    #     - 8080:8080
    links:
      - db:${DB_HOST:-db}
      - balancer:${DORIS_HOST:-doris}
    environment:
      OLAP_REDIS_DATABASE: 1
      OLAP_REDIS_HOST: "redis"
      OLAP_REDIS_PORT: 6379
      OLAP_REDIS_PASSWORD: ${REDIS_PASSWORD:-}
    networks:
      - overlay
      - doris_net
  api:
    image: registry.cn-hangzhou.aliyuncs.com/metad/metad-api:1.6.9
    container_name: metad-api
    environment:
      INSTALLATION_MODE: with-doris
      HOST: ${API_HOST:-api}
      PORT: ${API_PORT:-3000}
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      OLAP_HOST: olap
      OLAP_PORT: 8080
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      DEMO: ${DEMO:-true}
      DORIS_HOST: ${DORIS_HOST:-doris}
      DORIS_PORT: 9030
      DORIS_USER: ${DORIS_USER:-root}
      DORIS_PASS: ${DORIS_PASS:-}
      DORIS_DATABASE: ${DORIS_DATABASE:-demo}
      DORIS_API_PORT: 8040
      SENTRY_DSN: ${SENTRY_DSN:-}
      LOGGER_LEVEL: ${LOGGER_LEVEL:-info}
    env_file:
      - .env
    command: ["node", "main.js"]
    restart: on-failure
    depends_on:
      - db
      - redis
    links:
      - db:${DB_HOST:-db}
      - balancer:${DORIS_HOST:-doris}
    ports:
      - 3000:3000
    volumes:
      - ./public:/srv/pangolin/apps/
    networks:
      - overlay
      - doris_net
  webapp:
    image: registry.cn-hangzhou.aliyuncs.com/metad/metad-webapp:1.6.9
    container_name: metad-webapp
    environment:
      HOST: ${WEB_HOST:-webapp}
      PORT: ${WEB_PORT:-4200}
      NODE_ENV: ${NODE_ENV:-development}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:3000}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL:-http://localhost:4200}
      SENTRY_DSN: ${SENTRY_DSN:-}
      DEFAULT_LATITUDE: ${DEFAULT_LATITUDE:-42.6459136}
      DEFAULT_LONGITUDE: ${DEFAULT_LONGITUDE:-23.3332736}
      DEFAULT_CURRENCY: ${DEFAULT_CURRENCY:-USD}
      API_HOST: ${API_HOST:-api}
      API_PORT: ${API_PORT:-3000}
    entrypoint: "./entrypoint.compose.sh"
    command: ["nginx", "-g", "daemon off;"]
    env_file:
      - .env
    restart: on-failure
    links:
      - api:${API_HOST:-api}
    depends_on:
      - api
    ports:
      - 80:80
    networks:
      - overlay

networks:
  overlay:
    driver: bridge
  doris_net:
    ipam:
      config:
        - subnet: 172.20.80.0/16
volumes:
  postgres_data:
